version: '3'

services:
  typesense:
    image: typesense/typesense:0.25.1  # Using a more stable version
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: --data-dir /data --api-key=admin --enable-cors
    environment:
      - TYPESENSE_API_KEY=admin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 3